// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dyxubTUcbBaVpeY8HbHVx1JJfursgWQ',
    appId: '1:636770032873:android:b4dd9eca7babb21cece478',
    messagingSenderId: '636770032873',
    projectId: 'gps-collection-app',
    databaseURL: 'https://gps-collection-app-default-rtdb.firebaseio.com',
    storageBucket: 'gps-collection-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUSsvATHMBOj8Ixc6CQMQDWpJ_IB7e2o',
    appId: '1:636770032873:ios:42a2873528a2cc12ece478',
    messagingSenderId: '636770032873',
    projectId: 'gps-collection-app',
    databaseURL: 'https://gps-collection-app-default-rtdb.firebaseio.com',
    storageBucket: 'gps-collection-app.appspot.com',
    iosClientId: '636770032873-m3uihl1bhs14rli5pjn2766ekoua3urk.apps.googleusercontent.com',
    iosBundleId: 'com.inceptrafay.gpsCollectionApp',
  );
}
